import React from 'react';

interface Section {
  _id: string;
  type: string;
  content: string;
}

interface SectionCardProps {
  section: Section;
  index: number;
  isSubmitted: boolean;
}

export default function SectionCard({ section, index, isSubmitted }: SectionCardProps) {
  const getSectionIcon = (type: string) => {
    switch (type.toLowerCase()) {
      case 'hero':
        return '🚀';
      case 'about':
        return 'ℹ️';
      case 'contact':
        return '📞';
      case 'services':
        return '⚙️';
      case 'testimonials':
        return '💬';
      case 'features':
        return '✨';
      case 'pricing':
        return '💰';
      case 'faq':
        return '❓';
      default:
        return '📄';
    }
  };

  const getSectionColor = (type: string) => {
    switch (type.toLowerCase()) {
      case 'hero':
        return 'bg-blue-100';
      case 'about':
        return 'bg-green-100';
      case 'contact':
        return 'bg-orange-100';
      case 'services':
        return 'bg-purple-100';
      case 'testimonials':
        return 'bg-yellow-100';
      case 'features':
        return 'bg-indigo-100';
      case 'pricing':
        return 'bg-emerald-100';
      case 'faq':
        return 'bg-gray-100';
      default:
        return 'bg-gray-100';
    }
  };

  return (
    <div
      className="bg-white border border-gray-200 rounded-lg shadow-sm hover:shadow-md transition-all duration-300 transform hover:-translate-y-1"
      style={{
        animationDelay: `${index * 100}ms`,
        animation: isSubmitted ? 'slideInUp 0.6s ease-out forwards' : 'none',
        opacity: isSubmitted ? 0 : 1
      }}
    >
      <div className="p-6">
        <div className="flex items-center mb-4">
          <div className={`w-12 h-12 rounded-lg ${getSectionColor(section.type)} flex items-center justify-center text-2xl mr-3`}>
            {getSectionIcon(section.type)}
          </div>
          <div className="flex-1">
            <h3 className="font-bold text-lg text-black capitalize">
              {section.type}
            </h3>
            <p className="text-sm text-gray-500">
              Section {index + 1}
            </p>
          </div>
        </div>
        
        <div className="bg-gray-50 rounded-lg p-4 border border-gray-100">
          <p className="text-gray-700 text-sm leading-relaxed">
            {section.content}
          </p>
        </div>

        <div className="mt-4 flex items-center justify-between text-xs text-gray-500">
          <span>Generated by AI</span>
          <span className="flex items-center space-x-1">
            <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
            <span>Ready</span>
          </span>
        </div>
      </div>
    </div>
  );
} 